services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - 5435:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
